spring:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    
  application:
    name: database-app
    

    
  dbhclservice: 
    jdbc-url: "jdbc:mysql://localhost:3306/hcl_employee?createDatabaseIfNotExist=true&autoreconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
    password: "password"
    username: "root"
    
  dbquinnoxservice: 
    jdbc-url: "jdbc:mysql://localhost:3306/quinnox_employee?createDatabaseIfNotExist=true&autoreconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull"
    password: "password"
    username: "root"


server:
  port: 8081