spring:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MariaDBDialect
      format_sql: true
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    
  application:
    name: database-app
  
  datasource:    url: jdbc:mysql://localhost:3306/default_tenant?createDatabaseIfNotExist=true
    password: "password"
    username: "root"

server:
  port: 8081
  
  
hibernate:
 multiTenancy=SCHEMA
 multi_tenant_connection_provider=com.example.demo.config.SchemaMultiTenantConnectionProvider